### PR TITLE
Add check facebook default image

### PR DESCRIPTION
**Pull request by SarahhhC**
1. When crawl facebook data, check if profile is default or not.
2. If default facebook image, profile would be our default.

### CODE REVIEW

**Comment by MechanicKim** [comment]
I reviewed it! I have a question!
pattern image is for detail and card view.
How about general information profile image?

**Comment by SarahhhC** [comment]
It should be handled by front for now.

**Comment by lyw0149** [comment]
Good change!!
Thank you sarah!
LGTM

**Comment by MechanicKim** [comment]
Good! Thanks @SarahhhC 
LGTM :hankey:

**Pull request merged**
